[package]
name = "keygen"
version = "0.2.0"
authors = ["James Tease <james@jamestease.co.uk>"]

[dependencies]
regex = "0.2"
crc = "1.5"
clap = "2.24"
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"